### ISSUE TITLE
 Error: Can't resolve 'net' in `node_modules/@supercharge/request-ip/dist`

### ISSUE THREAD

**Issue by dmitrizzle** [supercharge/request-ip#2]
Can't run the package, keep getting 'module not found' error for `net`. Observed with 1.1.2

**Comment by marcuspoehls** [comment]
@dmitrizzle Hey, this package uses the Node.js `net` module to determine whether a given IP is a v4 or v6 address. Does this package have access to the Node.js environment? Or are you bundling this package with Webpack?

**Comment by dmitrizzle** [comment]
Hey @marcuspoehls I'm using it on the server side with Next.js - I've installed `net` and that fixed the error.

**Comment by marcuspoehls** [comment]
@dmitrizzle Sweet! Thank you for sharing your solution!
