### ISSUE TITLE
Filter internal addresses from X-Forwarded-For (and the like)

### ISSUE THREAD

**Issue by dmitrif** [supercharge/request-ip#3]
Linking relevant ticket from upstream repo: https://github.com/pbojinov/request-ip/issues/24

Would be a great feature. Let me know if you don't have time and I can push a PR.

**Comment by marcuspoehls** [comment]
@dmitrif Hey Dmitri, sounds good. I like the idea 😃 

Would be great if you can create a pull request 👍

**Comment by marcuspoehls** [comment]
Closing this issue because I currently don’t have time to implement this. Please re-open this issue or a pull request adding this feature in the future :)
